### ISSUE TITLE
Link Amazon account in iOS

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki-bar/tiki-capture-receipt-capacitor#36]
As a developer
I need to link a retail account
So that I can grab the user orders

### What it is now
There is no retail account linking

### What it should be 
The Linking class created in tiki-bar/tiki-capture-receipt-capacitor #34  should have the method to link a retailer account, and handle errors.

### Acceptance criteria
The Linking class can link an Amazon account

**Comment by ricardobrg** [comment]
closed as duplicate #55
