### ISSUE TITLE
Link retailer accounts

### ISSUE THREAD

**Issue by mike-audi** [tiki-bar/tiki-capture-receipt-capacitor#7]
Following the same pattern used for linking IMAP accounts, we need to configure the Microblink SDK for linking retailer accounts. 

Android instructions: https://github.com/BlinkReceipt/blinkreceipt-android/tree/master/blinkreceipt-account-linking
iOS instructions: https://blinkreceipt.github.io/blinkereceipt-ios/account-linking.html

**Comment by Schuler-Gabriel** [comment]
researching the documentation to create stories for implementation

**Comment by ricardobrg** [comment]
issues for Android created in #39, #40, #41, #42

**Comment by ricardobrg** [comment]
assigning to myself because i need to create iOS stories with @JesseMonteiro

**Comment by ricardobrg** [comment]
iOS #37 #39 #54  #55
